"""initial_schema

Revision ID: a47487410e56
Revises: 
Create Date: 2026-05-04 05:02:39.790231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
# revision identifiers, used by Alembic.
revision: str = 'a47487410e56'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('binders',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('origin_region', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('community_key', sa.String(length=200), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_binders_community_key'), 'binders', ['community_key'], unique=True)
    op.create_table('countries',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('iso_code', sa.String(length=3), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('community_key', sa.String(length=200), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_countries_community_key'), 'countries', ['community_key'], unique=True)
    op.create_table('environments',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('community_key', sa.String(length=200), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_environments_community_key'), 'environments', ['community_key'], unique=True)
    op.create_table('fillers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('priming', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('community_key', sa.String(length=200), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fillers_community_key'), 'fillers', ['community_key'], unique=True)
    op.create_table('flavor_tags',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('community_key', sa.String(length=200), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flavor_tags_community_key'), 'flavor_tags', ['community_key'], unique=True)
    op.create_table('manufacturers',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('community_key', sa.String(length=200), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_manufacturers_community_key'), 'manufacturers', ['community_key'], unique=True)
    op.create_table('purchase_types',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('community_key', sa.String(length=200), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_types_community_key'), 'purchase_types', ['community_key'], unique=True)
    op.create_table('strength_levels',
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('community_key', sa.String(length=200), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strength_levels_community_key'), 'strength_levels', ['community_key'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('sharing_defaults', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('api_key', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('vitolas',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('length_inches', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('ring_gauge', sa.Integer(), nullable=True),
    sa.Column('category', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('community_key', sa.String(length=200), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vitolas_community_key'), 'vitolas', ['community_key'], unique=True)
    op.create_table('wrappers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('color_category', sa.String(length=30), nullable=True),
    sa.Column('origin_region', sa.String(length=100), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('community_key', sa.String(length=200), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wrappers_community_key'), 'wrappers', ['community_key'], unique=True)
    op.create_table('brands',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('manufacturer_id', sa.UUID(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('community_key', sa.String(length=200), nullable=True),
    sa.Column('is_imported', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brands_community_key'), 'brands', ['community_key'], unique=True)
    op.create_table('guest_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_accessed', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_table('humidors',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('target_humidity', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('target_temp_f', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swaps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('partner_name', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cigars',
    sa.Column('community_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('line', sa.String(length=200), nullable=True),
    sa.Column('vitola_id', sa.UUID(), nullable=True),
    sa.Column('custom_vitola_name', sa.String(length=100), nullable=True),
    sa.Column('custom_length', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('custom_ring_gauge', sa.Integer(), nullable=True),
    sa.Column('wrapper_id', sa.UUID(), nullable=True),
    sa.Column('binder_id', sa.UUID(), nullable=True),
    sa.Column('country_id', sa.UUID(), nullable=True),
    sa.Column('manufacturer_id', sa.UUID(), nullable=True),
    sa.Column('strength_id', sa.UUID(), nullable=True),
    sa.Column('upc', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_user_created', sa.Boolean(), nullable=False),
    sa.Column('submission_status', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['manufacturers.id'], ),
    sa.ForeignKeyConstraint(['strength_id'], ['strength_levels.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vitola_id'], ['vitolas.id'], ),
    sa.ForeignKeyConstraint(['wrapper_id'], ['wrappers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cigars_user_brand', 'cigars', ['user_id', 'brand_id'], unique=False)
    op.create_table('humidor_readings',
    sa.Column('humidor_id', sa.UUID(), nullable=False),
    sa.Column('humidity', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('temperature_f', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['humidor_id'], ['humidors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_readings_humidor_recorded', 'humidor_readings', ['humidor_id', 'recorded_at'], unique=False)
    op.create_table('cigar_external_ratings',
    sa.Column('cigar_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('source_name', sa.String(length=100), nullable=False),
    sa.Column('score', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('review_url', sa.String(length=500), nullable=True),
    sa.Column('review_date', sa.Date(), nullable=True),
    sa.Column('reviewer_name', sa.String(length=100), nullable=True),
    sa.Column('personal_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ratings_cigar_user', 'cigar_external_ratings', ['cigar_id', 'user_id'], unique=False)
    op.create_table('cigar_fillers',
    sa.Column('cigar_id', sa.UUID(), nullable=False),
    sa.Column('filler_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigars.id'], ),
    sa.ForeignKeyConstraint(['filler_id'], ['fillers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cigar_id', 'filler_id', name='uq_cigar_fillers_cigar_filler')
    )
    op.create_table('cigar_images',
    sa.Column('cigar_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_type', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('contributed', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_cigar_images_cigar', 'cigar_images', ['cigar_id', 'sort_order'], unique=False)
    op.create_table('inventory',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cigar_id', sa.UUID(), nullable=False),
    sa.Column('humidor_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('price_per_stick', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('vendor', sa.String(length=200), nullable=True),
    sa.Column('vendor_url', sa.String(length=500), nullable=True),
    sa.Column('purchase_type_id', sa.UUID(), nullable=True),
    sa.Column('box_code', sa.String(length=50), nullable=True),
    sa.Column('date_added_humidor', sa.Date(), nullable=True),
    sa.Column('is_gift', sa.Boolean(), nullable=False),
    sa.Column('gift_from', sa.String(length=200), nullable=True),
    sa.Column('gift_occasion', sa.String(length=200), nullable=True),
    sa.Column('gift_to', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigars.id'], ),
    sa.ForeignKeyConstraint(['humidor_id'], ['humidors.id'], ),
    sa.ForeignKeyConstraint(['purchase_type_id'], ['purchase_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inventory_user_cigar', 'inventory', ['user_id', 'cigar_id'], unique=False)
    op.create_index('ix_inventory_user_humidor', 'inventory', ['user_id', 'humidor_id'], unique=False)
    op.create_table('inventory_transfers',
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('from_humidor_id', sa.UUID(), nullable=True),
    sa.Column('to_humidor_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('transferred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['from_humidor_id'], ['humidors.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['to_humidor_id'], ['humidors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('smoking_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cigar_id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=True),
    sa.Column('smoked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('environment_id', sa.UUID(), nullable=True),
    sa.Column('occasion', sa.String(length=200), nullable=True),
    sa.Column('personal_rating', sa.Integer(), nullable=True),
    sa.Column('would_buy_again', sa.Boolean(), nullable=True),
    sa.Column('add_to_want_list', sa.Boolean(), nullable=False),
    sa.Column('shared_to_community', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigars.id'], ),
    sa.ForeignKeyConstraint(['environment_id'], ['environments.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sessions_user_cigar', 'smoking_sessions', ['user_id', 'cigar_id'], unique=False)
    op.create_index('ix_sessions_user_smoked_at', 'smoking_sessions', ['user_id', 'smoked_at'], unique=False)
    op.create_table('swap_items',
    sa.Column('swap_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('cigar_id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigars.id'], ),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['swap_id'], ['swaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('swap_list_items',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('inventory_id', sa.UUID(), nullable=False),
    sa.Column('max_quantity', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pairings',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['smoking_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('session_flavor_tags',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('third', sa.String(length=10), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['smoking_sessions.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['flavor_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'tag_id', 'third', name='uq_session_flavor_tags_session_tag_third')
    )
    op.create_table('tasting_notes',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('draw_quality', sa.String(length=20), nullable=True),
    sa.Column('burn_quality', sa.String(length=20), nullable=True),
    sa.Column('ash_color', sa.String(length=20), nullable=True),
    sa.Column('ash_hold', sa.String(length=20), nullable=True),
    sa.Column('strength_first_id', sa.UUID(), nullable=True),
    sa.Column('strength_second_id', sa.UUID(), nullable=True),
    sa.Column('strength_third_id', sa.UUID(), nullable=True),
    sa.Column('flavor_first', sa.Text(), nullable=True),
    sa.Column('flavor_second', sa.Text(), nullable=True),
    sa.Column('flavor_third', sa.Text(), nullable=True),
    sa.Column('overall_notes', sa.Text(), nullable=True),
    sa.Column('retrohale_notes', sa.Text(), nullable=True),
    sa.Column('finish', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['smoking_sessions.id'], ),
    sa.ForeignKeyConstraint(['strength_first_id'], ['strength_levels.id'], ),
    sa.ForeignKeyConstraint(['strength_second_id'], ['strength_levels.id'], ),
    sa.ForeignKeyConstraint(['strength_third_id'], ['strength_levels.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id')
    )
    op.create_table('want_list',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('cigar_id', sa.UUID(), nullable=True),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('target_price', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('fulfilled', sa.Boolean(), nullable=False),
    sa.Column('fulfilled_inventory_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['cigar_id'], ['cigars.id'], ),
    sa.ForeignKeyConstraint(['fulfilled_inventory_id'], ['inventory.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['smoking_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('want_list')
    op.drop_table('tasting_notes')
    op.drop_table('session_flavor_tags')
    op.drop_table('pairings')
    op.drop_table('swap_list_items')
    op.drop_table('swap_items')
    op.drop_index('ix_sessions_user_smoked_at', table_name='smoking_sessions')
    op.drop_index('ix_sessions_user_cigar', table_name='smoking_sessions')
    op.drop_table('smoking_sessions')
    op.drop_table('inventory_transfers')
    op.drop_index('ix_inventory_user_humidor', table_name='inventory')
    op.drop_index('ix_inventory_user_cigar', table_name='inventory')
    op.drop_table('inventory')
    op.drop_index('ix_cigar_images_cigar', table_name='cigar_images')
    op.drop_table('cigar_images')
    op.drop_table('cigar_fillers')
    op.drop_index('ix_ratings_cigar_user', table_name='cigar_external_ratings')
    op.drop_table('cigar_external_ratings')
    op.drop_index('ix_readings_humidor_recorded', table_name='humidor_readings')
    op.drop_table('humidor_readings')
    op.drop_index('ix_cigars_user_brand', table_name='cigars')
    op.drop_table('cigars')
    op.drop_table('swaps')
    op.drop_table('humidors')
    op.drop_table('guest_links')
    op.drop_index(op.f('ix_brands_community_key'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_wrappers_community_key'), table_name='wrappers')
    op.drop_table('wrappers')
    op.drop_index(op.f('ix_vitolas_community_key'), table_name='vitolas')
    op.drop_table('vitolas')
    op.drop_table('users')
    op.drop_index(op.f('ix_strength_levels_community_key'), table_name='strength_levels')
    op.drop_table('strength_levels')
    op.drop_index(op.f('ix_purchase_types_community_key'), table_name='purchase_types')
    op.drop_table('purchase_types')
    op.drop_index(op.f('ix_manufacturers_community_key'), table_name='manufacturers')
    op.drop_table('manufacturers')
    op.drop_index(op.f('ix_flavor_tags_community_key'), table_name='flavor_tags')
    op.drop_table('flavor_tags')
    op.drop_index(op.f('ix_fillers_community_key'), table_name='fillers')
    op.drop_table('fillers')
    op.drop_index(op.f('ix_environments_community_key'), table_name='environments')
    op.drop_table('environments')
    op.drop_index(op.f('ix_countries_community_key'), table_name='countries')
    op.drop_table('countries')
    op.drop_index(op.f('ix_binders_community_key'), table_name='binders')
    op.drop_table('binders')
    # ### end Alembic commands ###
